name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync LeetCode submissions
        uses: ashutosh1906/leetcode-sync@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.CSRF_TOKEN }}
          destination-folder: leetcode
